### PR TITLE
Changed latest news date to the correct date

### PR DESCRIPTION
**Pull request by MonstoBusta**
Sorry, forgot to change this!

### CODE REVIEW

**Comment by davidgrieser** [comment]
I was really confused looking at the post on the main site and came to find a way to report this issue on the date. Glad to see there is a open PR for it. Hopefully it is merged soon.

**Comment by nisehime** [comment]
Uh, I hate to say it, but I guess we need another PR... Because it's February, not Februrary

**Comment by lakulish** [comment]
I'll fix, thanks!

**Comment by MonstoBusta** [comment]
> **[nisehime](/nisehime) ** commented

And I'm supposed to be an English Major, curses!

**Pull request merged**
